# Generated by Django 4.2.11 on 2024-03-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
